version: '3.9'

networks:
  dbnetwork:
    external: true      

# Reusable shared config
x-pg-deploy-shared: &pg-deploy-shared
  mode: replicated
  replicas: 1
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 5
    window: 60s    

x-env-shared: &env-shared
  ports: 
    - 5432
  networks:
    - dbnetwork
  # After 10 restarts don't try it again, otherwise it could affect other services on the host machine by restarting infinitely
  restart: on-failure:10
  # Limit the logging files to 10 with 100mb each, otherwise there is no limit until the disk is full
  logging:
    driver: "json-file"
    options:
      max-size: "100mb"
      max-file: "10"
  env_file:
    - ./pg_var.env


x-pg-shared: &pg-shared
  build:
    context: .
    dockerfile: ./Dockerfile.Postgis
  <<: *env-shared

services:
  pg-0:
    hostname: pg-0
    deploy:
      placement:
        constraints: [node.role == manager]
      <<: *pg-deploy-shared
    volumes:
      - pg_master_data:/bitnami/postgresql
      - type: bind # use bind mode otherwise the sh file is mounted as a folder
        source: ./scripts/init_db.sh
        target: /docker-entrypoint-initdb.d/init_db.sh
        
      - type: bind # use bind mode otherwise the sh file is mounted as a folder
        source: ./scripts/init_hero.sql
        target: /docker-entrypoint-initdb.d/init_hero.sql

    environment:
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_NODE_NAME=pg-0
    <<: *pg-shared

  pg-1:
    hostname: pg-1
    deploy:
      placement:
        constraints:
          - node.hostname==slave-node01
      <<: *pg-deploy-shared
    volumes:
      - pg_slave01_data:/bitnami/postgresql
    environment:
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    <<: *pg-shared

  pg-2:
    hostname: pg-2
    deploy:
      placement:
        constraints:
          - node.hostname==slave-node02
      <<: *pg-deploy-shared
    volumes:
      - pg_slave02_data:/bitnami/postgresql
    environment:
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
    <<: *pg-shared

  pgpool:
    image: docker.io/bitnami/pgpool:4
    hostname: pgpool
    deploy:
      placement:
        constraints: [node.role == manager]
      <<: *pg-deploy-shared
    ports:
      - 5432:5432
    depends_on:
      - pg-0
      - pg-1
      - pg-2
    env_file:
      - ./pg_pool.env
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dbnetwork
    # After 10 restarts don't try it again, otherwise it could affect other services on the host machine by restarting infinitely
    restart:
      on-failure:10
    # Limit the logging files to 10 with 100mb each, otherwise there is no limit until the disk is full
    logging:
      driver: "json-file"
      options:
        max-size: "100mb"
        max-file: "10"

volumes:
  pg_master_data:
    driver: local
  pg_slave01_data:
    driver: local
  pg_slave02_data:
    driver: local